//
//  DemoInteractor.swift
//  Search
//
//  Created by Atthachai 'Joe' Meethong on 22/8/2562 BE.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DemoBusinessLogic {
  func doSomething(request: Demo.Something.Request)
}

protocol DemoDataStore {
  //var name: String { get set }
}

class DemoInteractor: DemoBusinessLogic, DemoDataStore {
  var presenter: DemoPresentationLogic?
  var worker: DemoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Demo.Something.Request) {
    worker = DemoWorker()
    worker?.doSomeWork()
    
    let response = Demo.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
