//
//  DemoPresenter.swift
//  Search
//
//  Created by Atthachai 'Joe' Meethong on 22/8/2562 BE.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DemoPresentationLogic {
  func presentSomething(response: Demo.Something.Response)
}

class DemoPresenter: DemoPresentationLogic {
  weak var viewController: DemoDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Demo.Something.Response) {
    let storyboard = UIStoryboard.init(name: "Main", bundle: nil)
    let searchResultsController = storyboard.instantiateViewController(withIdentifier: "SearchResultsViewController") as! SearchResultsViewController
    let searchController = CustomSearchController(searchResultsController: searchResultsController)
    searchController.searchBar.placeholder = "Search Something ..."
    let viewModel = Demo.Something.ViewModel(searchController: searchController)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
