//
//  DemoModels.swift
//  Search
//
//  Created by Atthachai 'Joe' Meethong on 22/8/2562 BE.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Demo {
  // MARK: Use cases
  
  enum Something {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
      let searchController: CustomSearchController
    }
  }
}
