//
//  SearchResultsWorker.swift
//  Search
//
//  Created by Atthachai 'Joe' Meethong on 22/8/2562 BE.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchResultsWorker {
  func doSomeWork(text: String) -> [String] {
    var results: [String] = []
    for charactor in text {
      results.append("\(charactor)")
    }
    return results
  }
}
