//
//  SearchResultsPresenter.swift
//  Search
//
//  Created by Atthachai 'Joe' Meethong on 22/8/2562 BE.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultsPresentationLogic {
  func presentSomething(response: SearchResults.Something.Response)
}

class SearchResultsPresenter: SearchResultsPresentationLogic {
  weak var viewController: SearchResultsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SearchResults.Something.Response) {
    let results = response.results.enumerated().map {"\($0.offset + 1) ~> \($0.element)"}
    let viewModel = SearchResults.Something.ViewModel(results: results)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
