//
//  SearchResultsInteractor.swift
//  Search
//
//  Created by Atthachai 'Joe' Meethong on 22/8/2562 BE.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultsBusinessLogic {
  func doSomething(request: SearchResults.Something.Request)
}

protocol SearchResultsDataStore {
  //var name: String { get set }
}

class SearchResultsInteractor: SearchResultsBusinessLogic, SearchResultsDataStore {
  var presenter: SearchResultsPresentationLogic?
  var worker: SearchResultsWorker = SearchResultsWorker()
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SearchResults.Something.Request) {
    guard let text = request.searchText else {
      return
    }
    let results = worker.doSomeWork(text: text)
    let response = SearchResults.Something.Response(results: results)
    presenter?.presentSomething(response: response)
  }
}
